#!/bin/bash
# OpenClaw Auto-Setup Script for Firebase Studio
# Run this in Firebase Studio terminal to install & configure OpenClaw

set -e

echo "🦞 OpenClaw Setup for Firebase Studio"
echo "======================================"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Functions
log_info() { echo -e "${GREEN}✓${NC} $1"; }
log_warn() { echo -e "${YELLOW}⚠${NC} $1"; }
log_error() { echo -e "${RED}✗${NC} $1"; }

# Check Node.js
echo "📦 Checking prerequisites..."
if ! command -v node &> /dev/null; then
    log_error "Node.js not found. Please install Node.js 18+ first."
    exit 1
fi
log_info "Node.js: $(node --version)"

if ! command -v npm &> /dev/null; then
    log_error "npm not found. Please install npm first."
    exit 1
fi
log_info "npm: $(npm --version)"

# Check pnpm (optional, preferred)
PNPM_AVAILABLE=false
if command -v pnpm &> /dev/null; then
    log_info "pnpm: $(pnpm --version)"
    PNPM_AVAILABLE=true
fi

echo ""
echo "📥 Installing OpenClaw CLI..."

# Install OpenClaw
if [ "$PNPM_AVAILABLE" = true ]; then
    pnpm add -g openclaw
else
    npm install -g openclaw
fi

log_info "OpenClaw CLI installed"

echo ""
echo "🔧 Initializing OpenClaw..."

# Create .env file
cat > .env << 'EOF'
# OpenClaw Environment Variables
# Generated by setup-firebase-studio.sh

# Firebase (Maton API) - Required for Firebase integration
MATON_API_KEY=fNEwqPnPmiR58CMu2HoU-1K7kdPDcMKf6hFSl4NDNURJWOcRQcZojTITsslt_4vZSLSRK4v_CQgusHsRn6lGl8i5Xm1Imam1Au8

# OpenClaw Configuration
OPENCLAW_HOME=$HOME/.openclaw
OPENCLAW_WORKSPACE=$PWD

# Optional: Slack Integration
# SLACK_BOT_TOKEN=xoxb-...

# Optional: Notion Integration
# NOTION_TOKEN=secret_...
EOF

log_info "Created .env file"

# Create .gitignore
cat > .gitignore << 'EOF'
# OpenClaw
.env
.openclaw/
*.log
node_modules/

# Firebase Studio
.idx/
.DS_Store
EOF

log_info "Created .gitignore"

echo ""
echo "📚 Installing Essential Skills..."

# Install core skills
clawhub install openclaw-cli 2>/dev/null || log_warn "openclaw-cli already installed"
clawhub install firebase 2>/dev/null || log_warn "firebase already installed"
clawhub install laravel 2>/dev/null || log_warn "laravel already installed"
clawhub install php 2>/dev/null || log_warn "php already installed"
clawhub install github 2>/dev/null || log_warn "github already installed"
clawhub install telegram 2>/dev/null || log_warn "telegram already installed"
clawhub install webhook-send 2>/dev/null || log_warn "webhook-send already installed"
clawhub install database-agent 2>/dev/null || log_warn "database-agent already installed"

log_info "Skills installed"

echo ""
echo "🏗️  Creating Workspace Structure..."

# Create directories
mkdir -p src
mkdir -p tests
mkdir -p config
mkdir -p storage
mkdir -p .openclaw/workspace

log_info "Directory structure created"

# Create basic Laravel-like structure (if starting fresh)
if [ ! -f "composer.json" ]; then
    echo ""
    echo "🎨 Creating Laravel project skeleton..."
    
    # Create basic config files
    cat > config/app.php << 'EOF'
<?php
return [
    'name' => env('APP_NAME', 'OpenClaw Laravel'),
    'env' => env('APP_ENV', 'production'),
    'debug' => (bool) env('APP_DEBUG', false),
    'url' => env('APP_URL', 'http://localhost'),
];
EOF

    log_info "Basic config created"
fi

# Create OpenClaw config
cat > .openclaw/openclaw.json << 'EOF'
{
  "agents": {
    "defaults": {
      "model": {
        "primary": "openrouter/google/lyria-3-pro-preview:free",
        "fallbacks": [
          "openrouter/free",
          "google/gemma-4-26b-a4b-it:free"
        ]
      }
    }
  },
  "channels": {
    "telegram": {
      "enabled": true,
      "groupPolicy": "open"
    }
  }
}
EOF

log_info "OpenClaw config created"

echo ""
echo "🚀 Starting OpenClaw Gateway..."

# Start gateway (background)
openclaw gateway start &
sleep 3

log_info "Gateway started"

echo ""
echo "======================================"
echo "✅ OpenClaw Setup Complete!"
echo "======================================"
echo ""
echo "📋 Next Steps:"
echo "   1. Run: openclaw status"
echo "   2. Run: gh auth login (for GitHub)"
echo "   3. Create Laravel project: composer create-project laravel/laravel ."
echo "   4. Connect Firebase: https://ctrl.maton.ai/connections"
echo ""
echo "📚 Documentation: https://docs.openclaw.ai"
echo "💬 Support: https://discord.gg/clawd"
echo ""
echo "🎉 Happy coding with OpenClaw + Firebase Studio!"
